/**
 * testConfig.ts — Test Data File
 *
 * This file holds ONLY test data (credentials, form values, search terms).
 * It does NOT contain any URLs or environment configuration.
 *
 * All URLs and environment settings are owned exclusively by playwright.config.ts.
 *
 * Separation of concerns:
 *   playwright.config.ts → WHERE to run (environment URLs, browsers, timeouts)
 *   testConfig.ts        → WHAT to test with (usernames, passwords, form data)
 */

export const testConfig = {
  // ── Credentials ──────────────────────────────────────────────────────────
  password: process.env.TEST_PASSWORD || 'Password123!',
  username: process.env.TEST_USERNAME || 'Abhishek Kumar',

  // ── UI Search Terms ───────────────────────────────────────────────────────
  searchCriteria: ['MacBook', 'HP', 'Samsung'],

  // ── Registration Form Data ────────────────────────────────────────────────
  registration: {
    firstName: process.env.REG_FIRST_NAME || 'Abhishek',
    lastName: process.env.REG_LAST_NAME || 'Kumar',
    address: process.env.REG_ADDRESS || '123 QA Test Lane',
    country: process.env.REG_COUNTRY || 'United States',
    state: process.env.REG_STATE || 'California',
    city: process.env.REG_CITY || 'San Francisco',
    zipcode: process.env.REG_ZIPCODE || '94101',
    mobile: process.env.REG_MOBILE || '1234567890',
    dobDay: process.env.REG_DOB_DAY || '10',
    dobMonth: process.env.REG_DOB_MONTH || '5',
    dobYear: process.env.REG_DOB_YEAR || '1995',
  },

  // ── Payment Data ─────────────────────────────────────────────────────────
  payment: {
    cardName: process.env.CARD_NAME || 'Abhishek Kumar',
    cardNumber: process.env.CARD_NUMBER || '4111111111111111',
    cvc: process.env.CARD_CVC || '311',
    expiryMonth: process.env.CARD_EXPIRY_MONTH || '12',
    expiryYear: process.env.CARD_EXPIRY_YEAR || '2030',
  },

  // ── Negative Test Data ───────────────────────────────────────────────────
  negative: {
    invalidEmail: 'invalid_email@example.com',
    invalidPassword: 'wrongpassword',
    invalidProduct: 'InvalidProductXYZ12345',
    outOfStockProduct: 'iMac',
    contactEmail: 'test_inquiry@example.com',
    contactEnquiry: 'This is a test inquiry generated by automated UI tests to verify the contact form functionality.',
    mismatchedPassword: 'wrongpassword',
  },

  // ── API Test Data ─────────────────────────────────────────────────────────
  // (URLs for the API services live in playwright.config.ts → environmentConfig)
  api: {
    userAgent: 'ToptalSDETTestAutomationProject/1.0 (abhishek.kumar@test.com)',

    // Data-driven cities for geocoding tests
    cities: [
      { name: 'London', expectedRegion: 'England' },
      { name: 'New York', expectedRegion: 'United States' },
      { name: 'Tokyo', expectedRegion: 'Japan' },
    ],

    // CRUD test payloads
    sampleLocation: {
      title: 'Central Park New York',
      body: 'Lat: 40.7829, Lon: -73.9654',
      userId: 1,
    },
    updatedLocation: {
      title: 'Central Park New York — Updated',
      body: 'Lat: 40.7850, Lon: -73.9680',
      userId: 1,
    },
  },

  // ── Stripe & Billing Test Data ───────────────────────────────────────────
  stripe: {
    apiKey: process.env.STRIPE_SECRET_KEY || 'sk_test_mock_secret_key_clinical_saas_platform',
    webhookSecret: process.env.STRIPE_WEBHOOK_SECRET || 'whsec_test_mock_webhook_secret_clinical_123',
    currency: 'usd',
    defaultAmountCents: 49900, // $499.00 (Clinical SaaS Monthly Tier)
    plans: {
      clinicalStarter: {
        id: 'price_clinical_starter_monthly',
        amountCents: 9900, // $99.00
        currency: 'usd',
        interval: 'month',
        name: 'Clinical AI Starter Tier',
      },
      clinicalPro: {
        id: 'price_clinical_pro_monthly',
        amountCents: 49900, // $499.00
        currency: 'usd',
        interval: 'month',
        name: 'Clinical AI Pro Tier (Real-time Transcription & HIPAA Audit)',
      },
      clinicalEnterprise: {
        id: 'price_clinical_enterprise_yearly',
        amountCents: 499900, // $4,999.00
        currency: 'usd',
        interval: 'year',
        name: 'Clinical AI Enterprise Tier (Unlimited Longitudinal Records)',
      },
    },
    testTokens: {
      successVisa: 'tok_visa',
      successMastercard: 'tok_mastercard',
      declinedGeneric: 'tok_chargeDeclined',
      declinedInsufficientFunds: 'tok_chargeDeclinedInsufficientFunds',
      declinedExpiredCard: 'tok_chargeDeclinedExpiredCard',
      declinedIncorrectCvc: 'tok_chargeDeclinedIncorrectCvc',
    },
  },
};

